// <auto-generated />
using System;
using ERPNet.Infrastructure.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ERPNet.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ERPNetDbContext))]
    [Migration("20260318103135_AgregarArticulos")]
    partial class AgregarArticulos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ERPNet.Domain.Entities.Archivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArchivoOriginalId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("EsThumbnail")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("Tamaño")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ArchivoOriginalId");

                    b.ToTable("Archivos");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ConfiguracionCaducidadId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<int?>("FamiliaArticuloId")
                        .HasColumnType("integer");

                    b.Property<int?>("FormatoArticuloId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("PrecioCompra")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("PrecioVenta")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int?>("TipoIvaId")
                        .HasColumnType("integer");

                    b.Property<string>("UnidadMedida")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionCaducidadId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("FamiliaArticuloId");

                    b.HasIndex("FormatoArticuloId");

                    b.HasIndex("TipoIvaId");

                    b.HasIndex("Codigo", "EmpresaId")
                        .IsUnique();

                    b.ToTable("articulos", (string)null);
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.ArticuloLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ArticuloId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("StockAnterior")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("StockNuevo")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("articulos_log", (string)null);
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.AsignacionTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaHasta")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("TurnoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("TurnoId");

                    b.ToTable("AsignacionesTurno");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.ConfiguracionCaducidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DiasAviso")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("configuraciones_caducidad", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiasAviso = 7,
                            Nombre = "7 días antes"
                        },
                        new
                        {
                            Id = 2,
                            DiasAviso = 15,
                            Nombre = "15 días antes"
                        },
                        new
                        {
                            Id = 3,
                            DiasAviso = 30,
                            Nombre = "30 días antes"
                        },
                        new
                        {
                            Id = 4,
                            DiasAviso = 60,
                            Nombre = "60 días antes"
                        },
                        new
                        {
                            Id = 5,
                            DiasAviso = 90,
                            Nombre = "90 días antes"
                        });
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<int?>("EncargadoId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FotoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SeccionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EncargadoId");

                    b.HasIndex("FotoId")
                        .IsUnique();

                    b.HasIndex("SeccionId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cif")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.FamiliaArticulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<int?>("FamiliaPadreId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("FamiliaPadreId");

                    b.ToTable("familias_articulo", (string)null);
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.FormatoArticulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("formatos_articulo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Unidad"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Caja"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Palet"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Kilogramo"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Litro"
                        });
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.IncidenciaMarcaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MarcajeId")
                        .HasColumnType("integer");

                    b.Property<int>("MinutosRetraso")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("ValidadaPorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MarcajeId")
                        .IsUnique();

                    b.HasIndex("ValidadaPorId");

                    b.ToTable("IncidenciasMarcaje");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoError")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Detalle")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Entidad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntidadId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.LogIntentoLogin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DireccionIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaIntento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("DireccionIp", "FechaIntento");

                    b.HasIndex("NombreUsuario", "FechaIntento");

                    b.ToTable("IntentosLogin");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Maquinaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CertificadoCeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FichaTecnicaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FotoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ManualId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("SeccionId")
                        .HasColumnType("integer");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CertificadoCeId")
                        .IsUnique();

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("EmpresaId");

                    b.HasIndex("FichaTecnicaId")
                        .IsUnique();

                    b.HasIndex("FotoId")
                        .IsUnique();

                    b.HasIndex("ManualId")
                        .IsUnique();

                    b.HasIndex("SeccionId");

                    b.ToTable("Maquinas");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Marcaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime?>("HoraEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HoraSalida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Marcajes");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("MenuPadreId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Plataforma")
                        .HasColumnType("integer");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MenuPadreId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.MenuRol", b =>
                {
                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("MenuId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("MenusRoles");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.OrdenMantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AsignadoAId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MaquinariaId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoMantenimientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AsignadoAId");

                    b.HasIndex("MaquinariaId");

                    b.HasIndex("TipoMantenimientoId");

                    b.ToTable("OrdenesMantenimiento");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.PermisoRolRecurso", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<int>("RecursoId")
                        .HasColumnType("integer");

                    b.Property<int>("Alcance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("CanCreate")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("RolId", "RecursoId");

                    b.HasIndex("RecursoId");

                    b.ToTable("PermisosRolRecurso");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Recurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Recursos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "Aplicacion"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "Empleados"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "Vacaciones"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "Turnos"
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "Marcajes"
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "Maquinaria"
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "Mantenimiento"
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "OrdenesFabrica"
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "Clientes"
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "Facturas"
                        },
                        new
                        {
                            Id = 11,
                            Codigo = "Empresas"
                        },
                        new
                        {
                            Id = 12,
                            Codigo = "AsistenteIa"
                        },
                        new
                        {
                            Id = 13,
                            Codigo = "Articulos"
                        });
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaRevocacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ReemplazadoPor")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.RolUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId", "RolId")
                        .IsUnique()
                        .HasDatabaseName("IX_RolUsuario_UsuarioId_RolId_Global")
                        .HasFilter("\"EmpresaId\" IS NULL");

                    b.HasIndex("UsuarioId", "RolId", "EmpresaId")
                        .IsUnique()
                        .HasDatabaseName("IX_RolUsuario_UsuarioId_RolId_Empresa")
                        .HasFilter("\"EmpresaId\" IS NOT NULL");

                    b.ToTable("RolesUsuarios");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Seccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ResponsableId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("ResponsableId");

                    b.ToTable("Secciones");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.TipoIva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Porcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.ToTable("tipos_iva", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "IVA 0%",
                            Porcentaje = 0m
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "IVA 4%",
                            Porcentaje = 4m
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "IVA 10%",
                            Porcentaje = 10m
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "IVA 21%",
                            Porcentaje = 21m
                        });
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.TipoMantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("TiposMantenimiento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "Correctivo"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "Preventivo"
                        });
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("DomingoEntrada")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("DomingoSalida")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly?>("JuevesEntrada")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("JuevesSalida")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("LunesEntrada")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("LunesSalida")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("MartesEntrada")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("MartesSalida")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("MiercolesEntrada")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("MiercolesSalida")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<TimeOnly?>("SabadoEntrada")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("SabadoSalida")
                        .HasColumnType("time without time zone");

                    b.Property<int>("ToleranciaMinutos")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("ViernesEntrada")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("ViernesSalida")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CaducidadContrasena")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UltimoCambioContrasena")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmpleadoId")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.UsuarioEmpresa", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("UsuarioId", "EmpresaId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("UsuarioEmpresas");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Vacacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AprobadoPorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AprobadoPorId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Vacaciones");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Archivo", b =>
                {
                    b.HasOne("ERPNet.Domain.Entities.Archivo", "ArchivoOriginal")
                        .WithMany("Thumbnails")
                        .HasForeignKey("ArchivoOriginalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ArchivoOriginal");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Articulo", b =>
                {
                    b.HasOne("ERPNet.Domain.Entities.ConfiguracionCaducidad", "ConfiguracionCaducidad")
                        .WithMany()
                        .HasForeignKey("ConfiguracionCaducidadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ERPNet.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPNet.Domain.Entities.FamiliaArticulo", "FamiliaArticulo")
                        .WithMany("Articulos")
                        .HasForeignKey("FamiliaArticuloId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ERPNet.Domain.Entities.FormatoArticulo", "FormatoArticulo")
                        .WithMany()
                        .HasForeignKey("FormatoArticuloId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ERPNet.Domain.Entities.TipoIva", "TipoIva")
                        .WithMany()
                        .HasForeignKey("TipoIvaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ConfiguracionCaducidad");

                    b.Navigation("Empresa");

                    b.Navigation("FamiliaArticulo");

                    b.Navigation("FormatoArticulo");

                    b.Navigation("TipoIva");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.ArticuloLog", b =>
                {
                    b.HasOne("ERPNet.Domain.Entities.Articulo", "Articulo")
                        .WithMany("Logs")
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPNet.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.AsignacionTurno", b =>
                {
                    b.HasOne("ERPNet.Domain.Entities.Empleado", "Empleado")
                        .WithMany("AsignacionesTurno")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPNet.Domain.Entities.Turno", "Turno")
                        .WithMany("AsignacionesTurno")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Empleado", b =>
                {
                    b.HasOne("ERPNet.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPNet.Domain.Entities.Empleado", "Encargado")
                        .WithMany("Subordinados")
                        .HasForeignKey("EncargadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERPNet.Domain.Entities.Archivo", "Foto")
                        .WithOne()
                        .HasForeignKey("ERPNet.Domain.Entities.Empleado", "FotoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ERPNet.Domain.Entities.Seccion", "Seccion")
                        .WithMany("Empleados")
                        .HasForeignKey("SeccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Encargado");

                    b.Navigation("Foto");

                    b.Navigation("Seccion");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.FamiliaArticulo", b =>
                {
                    b.HasOne("ERPNet.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPNet.Domain.Entities.FamiliaArticulo", "FamiliaPadre")
                        .WithMany("SubFamilias")
                        .HasForeignKey("FamiliaPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empresa");

                    b.Navigation("FamiliaPadre");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.IncidenciaMarcaje", b =>
                {
                    b.HasOne("ERPNet.Domain.Entities.Marcaje", "Marcaje")
                        .WithOne("Incidencia")
                        .HasForeignKey("ERPNet.Domain.Entities.IncidenciaMarcaje", "MarcajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPNet.Domain.Entities.Empleado", "ValidadaPor")
                        .WithMany()
                        .HasForeignKey("ValidadaPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Marcaje");

                    b.Navigation("ValidadaPor");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Log", b =>
                {
                    b.HasOne("ERPNet.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Logs")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.LogIntentoLogin", b =>
                {
                    b.HasOne("ERPNet.Domain.Entities.Usuario", "Usuario")
                        .WithMany("IntentosLogin")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Maquinaria", b =>
                {
                    b.HasOne("ERPNet.Domain.Entities.Archivo", "CertificadoCe")
                        .WithOne()
                        .HasForeignKey("ERPNet.Domain.Entities.Maquinaria", "CertificadoCeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ERPNet.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPNet.Domain.Entities.Archivo", "FichaTecnica")
                        .WithOne()
                        .HasForeignKey("ERPNet.Domain.Entities.Maquinaria", "FichaTecnicaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ERPNet.Domain.Entities.Archivo", "Foto")
                        .WithOne()
                        .HasForeignKey("ERPNet.Domain.Entities.Maquinaria", "FotoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ERPNet.Domain.Entities.Archivo", "Manual")
                        .WithOne()
                        .HasForeignKey("ERPNet.Domain.Entities.Maquinaria", "ManualId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ERPNet.Domain.Entities.Seccion", "Seccion")
                        .WithMany("Maquinarias")
                        .HasForeignKey("SeccionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CertificadoCe");

                    b.Navigation("Empresa");

                    b.Navigation("FichaTecnica");

                    b.Navigation("Foto");

                    b.Navigation("Manual");

                    b.Navigation("Seccion");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Marcaje", b =>
                {
                    b.HasOne("ERPNet.Domain.Entities.Empleado", "Empleado")
                        .WithMany("Marcajes")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Menu", b =>
                {
                    b.HasOne("ERPNet.Domain.Entities.Menu", "MenuPadre")
                        .WithMany("SubMenus")
                        .HasForeignKey("MenuPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MenuPadre");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.MenuRol", b =>
                {
                    b.HasOne("ERPNet.Domain.Entities.Menu", "Menu")
                        .WithMany("MenusRoles")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPNet.Domain.Entities.Rol", "Rol")
                        .WithMany("MenusRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.OrdenMantenimiento", b =>
                {
                    b.HasOne("ERPNet.Domain.Entities.Empleado", "AsignadoA")
                        .WithMany()
                        .HasForeignKey("AsignadoAId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ERPNet.Domain.Entities.Maquinaria", "Maquinaria")
                        .WithMany("OrdenesMantenimiento")
                        .HasForeignKey("MaquinariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPNet.Domain.Entities.TipoMantenimiento", "TipoMantenimiento")
                        .WithMany("OrdenesMantenimiento")
                        .HasForeignKey("TipoMantenimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AsignadoA");

                    b.Navigation("Maquinaria");

                    b.Navigation("TipoMantenimiento");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.PermisoRolRecurso", b =>
                {
                    b.HasOne("ERPNet.Domain.Entities.Recurso", "Recurso")
                        .WithMany("PermisosRolRecurso")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPNet.Domain.Entities.Rol", "Rol")
                        .WithMany("PermisosRolRecurso")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recurso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ERPNet.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.RolUsuario", b =>
                {
                    b.HasOne("ERPNet.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERPNet.Domain.Entities.Rol", "Rol")
                        .WithMany("RolesUsuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPNet.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RolesUsuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Seccion", b =>
                {
                    b.HasOne("ERPNet.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPNet.Domain.Entities.Empleado", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Empresa");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("ERPNet.Domain.Entities.Empleado", "Empleado")
                        .WithOne("Usuario")
                        .HasForeignKey("ERPNet.Domain.Entities.Usuario", "EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.UsuarioEmpresa", b =>
                {
                    b.HasOne("ERPNet.Domain.Entities.Empresa", "Empresa")
                        .WithMany("UsuarioEmpresas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPNet.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioEmpresas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Vacacion", b =>
                {
                    b.HasOne("ERPNet.Domain.Entities.Empleado", "AprobadoPor")
                        .WithMany()
                        .HasForeignKey("AprobadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERPNet.Domain.Entities.Empleado", "Empleado")
                        .WithMany("Vacaciones")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AprobadoPor");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Archivo", b =>
                {
                    b.Navigation("Thumbnails");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Articulo", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Empleado", b =>
                {
                    b.Navigation("AsignacionesTurno");

                    b.Navigation("Marcajes");

                    b.Navigation("Subordinados");

                    b.Navigation("Usuario");

                    b.Navigation("Vacaciones");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("UsuarioEmpresas");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.FamiliaArticulo", b =>
                {
                    b.Navigation("Articulos");

                    b.Navigation("SubFamilias");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Maquinaria", b =>
                {
                    b.Navigation("OrdenesMantenimiento");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Marcaje", b =>
                {
                    b.Navigation("Incidencia");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Menu", b =>
                {
                    b.Navigation("MenusRoles");

                    b.Navigation("SubMenus");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Recurso", b =>
                {
                    b.Navigation("PermisosRolRecurso");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Rol", b =>
                {
                    b.Navigation("MenusRoles");

                    b.Navigation("PermisosRolRecurso");

                    b.Navigation("RolesUsuarios");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Seccion", b =>
                {
                    b.Navigation("Empleados");

                    b.Navigation("Maquinarias");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.TipoMantenimiento", b =>
                {
                    b.Navigation("OrdenesMantenimiento");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Turno", b =>
                {
                    b.Navigation("AsignacionesTurno");
                });

            modelBuilder.Entity("ERPNet.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("IntentosLogin");

                    b.Navigation("Logs");

                    b.Navigation("RefreshTokens");

                    b.Navigation("RolesUsuarios");

                    b.Navigation("UsuarioEmpresas");
                });
#pragma warning restore 612, 618
        }
    }
}
